V0.2
iElden/IndieStudio pull request #10
Opened 2019-06-12 16:11 UTC by iElden

2019-06-13 08:31 UTC, SunniestJune commented on src/ecs/components/BombDropperComponent.cpp
> +		Component ("BombDropper"),
y'a un espace entre le component et sa parenthèse

2019-06-13 08:43 UTC, SunniestJune commented on src/ecs/entities/Bomb.cpp
> +#include "../components/BlockedComponent.hpp"
BlockedComponent.hpp include to be removed

2019-06-13 08:44 UTC, SunniestJune commented on src/ecs/entities/Brick.cpp
> +#include "../components/MortalComponent.hpp"
MortalComponent.hpp include to be removed

2019-06-13 08:45 UTC, SunniestJune commented on src/ecs/entities/Brick.cpp
> +#include "../components/MortalComponent.hpp"
BlockedComponent include to be removed

2019-06-13 08:48 UTC, SunniestJune commented on src/ecs/entities/DroppedItem.cpp
> +ECS::DroppedItem::DroppedItem(unsigned id, Ressources &ressources) :
I don't know if the DroppedItem entity is used. If not, i think we can just remove it

2019-06-13 08:50 UTC, SunniestJune commented on src/ecs/entities/DroppedItem.cpp
> +ECS::DroppedItem::DroppedItem(unsigned id, Ressources &ressources) :
Or maybe inheritate him for the dropped bonus ? I don't know, let you choose

2019-06-13 09:25 UTC, SunniestJune reviewed
Some of the includes to be erased, and maybe the deletion of the DroppedItem entity, because i d'ont know if we are using it

2019-06-13 09:25 UTC, SunniestJune commented on src/ecs/entities/Player.cpp
> +        new CurseComponent(ressources.soundSystem),
Tabs consistency is not respected here be careful + ult invicibility included but i think it's not an include error but done in purpose ?
- Power up Component include to be removed

2019-06-13 09:25 UTC, SunniestJune commented on src/ecs/entities/Skull.cpp
> +#include "../components/PowerUpPickedComponent.hpp"
PowerUpComponent include + PowerUpPickedComponent include to be removed

2019-06-13 09:25 UTC, SunniestJune commented on src/ecs/entities/Wall.cpp
> +#include "../components/BlockedComponent.hpp"
blockedComponent include to remove

2019-06-13 09:25 UTC, SunniestJune commented on src/ecs/factories/ComponentFactory.cpp
> +		{"Picker", [](Ressources &ressources, std::istream &stream) { return new PickerComponent(ressources, stream); }},
tabs consistency

2019-06-13 09:25 UTC, SunniestJune commented on src/ecs/factories/SystemFactory.cpp
> +        {"Pickable", [](ECS::ECSCore &core) { return new PickableSystem(core); }},
tabs consistency

2019-06-13 09:40 UTC, Zargith submitted a review, later dismissed

2019-06-13 12:50 UTC, EternalDrake commented on src/ecs/components/BombDropperComponent.cpp
> +		Component ("BombDropper"),
@SunniestJune ragix

2019-06-13 12:51 UTC, EbenStream submitted a review, later dismissed

2019-06-13 13:04 UTC, Zargith commented
Utiliser le modèle de sphère pour les bonus plutôt que des cubes. Utiliser le modèle de skull pour les bonus plutôt que des cubes.

2019-06-13 13:06 UTC, EternalDrake commented on src/ecs/systems/ExplodeSystem.cpp
> +ECS::ExplodeSystem::ExplodeSystem(ECS::ECSCore &core) :
C'est trop long j'ai le temps de passer Challenger sur league avant que ça exploque réduisez le temps ça sauve des chatons bordel de merde

2019-06-13 13:07 UTC, Zargith commented on src/irrlicht/game-scene/irr-entity/IrrEntity.cpp
> +        _meshPath("./media/models/" + filename + ".md2"),
Utiliser le modèle de sphère pour les bonus plutôt que des cubes. Utiliser le modèle de skull pour les bonus plutôt que des cubes.

2019-06-13 13:07 UTC, Zargith requested changes
Utiliser le modèle de sphère pour les bonus plutôt que des cubes. Utiliser le modèle de skull pour les bonus plutôt que des cubes.

2019-06-13 13:08 UTC, EbenStream requested changes
"Je pars pour gamelon pour l'aider.
Si la bombe n'a pas encore explosé au matin, envoie Link."

2019-06-13 13:28 UTC, PinkySmile requested changes

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/ExplodeComponent.hpp
> +	        Sound::SoundSystem &soundSystem;
Là il y a un tab

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/OOBKillComponent.cpp
> +        OOBKillComponent({0, 0}, {0, 0})
8 espaces au lieu de 4

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/OnCollisionDamageDealerComponent.cpp
> +	    stream >> damage >> terminator;
Indentation inconsistante

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/PickableComponent.cpp
> +	    PickableComponent()
Tab

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/PickerComponent.cpp
> +	    PickerComponent()
tab

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/entities/DroppedItem.cpp
> +ECS::DroppedItem::DroppedItem(unsigned id, Ressources &ressources) :
Faire hériter tous les bonus de DroppedItem et donner les bonus (std::map<std::string, NumericValue>) dans le constructeur

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/entities/DroppedItem.hpp
> +        explicit DroppedItem(unsigned id, Ressources &ressources);
Ajouter les bonus à appliquer au joueur quand ramassé dans le constructeur

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/factories/ComponentFactory.cpp
> +        {"CurseOnPick", [](Ressources &ressources, std::istream &stream) { return new CurseOnPickComponent(ressources, stream); }},
Espaces au lieu de tabs

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/factories/ComponentFactory.cpp
> +        {"OOBKill", [](Ressources &ressources, std::istream &stream) { return new OOBKillComponent(ressources, stream); }},
Espaces au lieu de tabs

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/factories/SystemFactory.cpp
> +        {"CurseOnPick", [](ECS::ECSCore &core) { return new CurseOnPickSystem(core); }},
Espaces au lieu de tabs

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/BlockedSystem.cpp
> +    	auto &entity_pos = reinterpret_cast<PositionComponent &>(entity.getComponentByName("Position"));
Tab au lieu d'espaces

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/BombDropperSystem.cpp
> +	for (int i = 0; i < (int)bomb.bombs.size(); i++) {
Passer i en unsigned au lieu de cast en int

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/BombDropperSystem.cpp
> +	ECS::BombDropperComponent &bomb = reinterpret_cast<ECS::BombDropperComponent &>(entity.getComponentByName("BombDropper"));
Renommer la variable bomb en bombDropper

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/components/BlockedComponent.hpp
> +        std::vector<Entity*> _whitelistId;
Les publics ne commencent pas par un underscore

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/CollisionSystem.cpp
> +    System("Collision", core)
4 espaces au lieu d'un tab

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/ControllableSystem.cpp
> +        auto &disp = reinterpret_cast<DisplayableComponent &>(entity.getComponentByName("Displayable"));
Espaces au lieu de tabs

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/CurseOnPickSystem.cpp
> +    auto curse = static_cast<CurseComponent::CurseEffect >(random_dev() % (CurseComponent::_NUMBER_OF_CURSE - 1) + 1);
Du coup on peut plus avoir CurseComponent::ULTRASPEED ?
Si c'est voulu l'enlever de l'enum sinon:
```cpp
auto curse = static_cast<CurseComponent::CurseEffect >(random_dev() % CurseComponent::_NUMBER_OF_CURSE);
```

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/CurseOnPickSystem.cpp
> +    auto curse = static_cast<CurseComponent::CurseEffect >(random_dev() % (CurseComponent::_NUMBER_OF_CURSE - 1) + 1);
Il y a un espace en trop avant le chevron fermant

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/CurseSystem.cpp
> +
Enlever la ligne vide ici

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/CurseSystem.cpp
> +    else if (cc.timeLeft == 0) {
Pourquoi ne pas vérifier que ce n'est pas CurseComponent::CurseEffect::NONE tout au début de la fonction et donc, de ne pas avoir à mettre le timeLeft à une valeur négative ?

2019-06-13 13:28 UTC, PinkySmile commented on src/ecs/systems/ExplodeSystem.cpp
> +        System("Explode", core)
Tab au lieu d'espaces

2019-06-13 13:28 UTC, Gegel85 commented on src/ecs/systems/MovableSystem.cpp
> +            mc.speed = (mc.speed <= mc.maxSpeed ? mc.speed : mc.maxSpeed);
Remplacer par
```cpp
else if (mc.speed > mc.maxSpeed)
    mc.speed = mc.maxSpeed;
```

2019-06-13 13:28 UTC, Gegel85 commented on src/input/Controller.cpp
> +        throw ControllerException("Invalid key vector given (size is invalid)");
Indentation inconsistante

2019-06-13 13:28 UTC, Gegel85 commented on src/input/Keyboard.cpp
> +       throw KeyboardException("Invalid number of keys");
Indentation inconsistante

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/Animations.hpp
> +		ULT_CAST = irr::scene::EMAT_STAND,
IDLE et ULT_CAST ont la même animation ?

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/Exceptions.cpp
> +#include "Exceptions.hpp"
Fichier inutile

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/GameScene.cpp
> +            ent->setAnimation(anim);
Indentation inconsistante

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/GameScene.cpp
> +			ent->setRotation(y);
throw quand pas d'entité trouvé + faire une fonction privé qui prend l'id en param et return l'entity correspondante, throw si non trouvé

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/GameScene.cpp
> +//	this->_eventReceiver.displayAxes();
Commentaire inutile

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/irr-entity/IrrEntity.cpp
> +        _meshPath("./media/models/" + filename + ".md2"),
Le modèle des skulls c'est pour les skulls, pas les power up.
Ce commentaire va dans DroppedBonus*.cpp

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/irr-hud/IrrHud.cpp
> +#include "IrrHud.hpp"
Useless file

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/irr-hud/IrrHud.hpp
> +#endif //BOMBERMAN_IRRHUD_HPP
Useless file

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/main-menu/MainMenu.cpp
> +#include "MainMenu.hpp"
Useless file

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/game-scene/main-menu/MainMenu.hpp
> +#endif //BOMBERMAN_MAINMENU_HPP
Useless file

2019-06-13 13:28 UTC, Gegel85 commented on src/irrlicht/screen/Screen.cpp
> +    this->_device->closeDevice();
Appeler setWindowAttributes au lieu de recopier

2019-06-13 14:12 UTC, EbenStream approved these changes

2019-06-13 14:41 UTC, Gegel85 commented on src/ecs/systems/CurseOnPickSystem.cpp
> +    auto curse = static_cast<CurseComponent::CurseEffect >(random_dev() % (CurseComponent::_NUMBER_OF_CURSE - 1) + 1);
Ok j'avais juste oublié que le 0 c'est NONE, j'ai rien dis

2019-06-13 15:22 UTC, PinkySmile approved these changes

2019-06-13 15:25 UTC, PinkySmile requested changes
En fait, il manque le binaire mingw32

2019-06-13 15:26 UTC, Zargith approved these changes

2019-06-14 08:20 UTC, PinkySmile approved these changes

2019-06-14 08:21 UTC, merged